# fly.toml file generated for stat-generator on 2022-10-17T17:08:13-04:00

app = "stat-generator"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  SECRET="itotheiis2.718totheminus3.14over2"
  DESMOS_API_KEY="dcb31709b452b1cf9dc26972add0fda6"
  RANDOM_API_KEY="06805c80-dbcc-472c-90e0-62d106a0b5ea"
  DEPLOYED_URL="mongodb+srv://mbaum:mongopass1211@cluster0.c4dao92.mongodb.net/stats?retryWrites=true&w=majority"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
